version: '3'
services:
  web:
    build: .
    command: python reverse-proxy-service.py
    ports:
     - 5000
    volumes:
      - .:/reverse-proxy
    links:
     - db


  db:
    image: mongo:3.0.2
    environment:
      MONGODB_HOST: db


  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
